version: "3"

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=eventtoolbox
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8081:8080

  redis:
    image: redis:alpine
    restart: always

  app:
    image: eventtoolbox
    restart: always
    build:
      context: .
    ports:
      - 0.0.0.0:${PORT}:8000
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db/eventtoolbox
      - BASE_URL=${BASE_URL}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
