version: "3"

services:
  db:
    image: postgres:10.2-alpine
    restart: always
    environment:
    - POSTGRES_PASSWORD=12345
    - POSTGRES_DB=eventfeedback_dev
    ports:
    - "127.0.0.1:5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
    - "127.0.0.1:8081:8080"
  redis:
    image: redis:alpine
    restart: always
    ports:
    - "127.0.0.1:6379:6379"
